application: ultra-simple-blog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

libraries:
- name: django
  version: latest

handlers:
- url: /css
  static_dir: media/css
    
- url: /.*
  script: djangoappengine.main.application